# ===========================================================================
# CONFIGURAÇÕES E DICIONÁRIOS GLOBAIS
# ==============================================================================

MARKETPLACES = {
    "ALIEXPRESS": "ALIEXPRESS", "AMAZON - EXTREMA": "AMAZON - EXTREMA",
    "AMAZON | ENGAGE LOG": "AMAZON | ENGAGE LOG", "AMERICANAS - EXTREMA": "AMERICANAS - EXTREMA",
    "B2W": "B2W", "CARREFOUR": "CARREFOUR", "CNOVA": "CNOVA", "CNOVA - EXTREMA": "CNOVA - EXTREMA",
    "FAST SHOP": "FAST SHOP", "MADEIRA MADEIRA": "MADEIRA MADEIRA", "MAGALU - EXTREMA": "MAGALU - EXTREMA",
    "MAGALU ELETRO": "MAGALU ELETRO", "MAGALU INFO": "MAGALU INFO", "MARTINS": "MARTINS",
    "MELI OUTLET": "MELI OUTLET", "MERCADO LIVRE": "MERCADO LIVRE",
    "MERCADO LIVRE - EXTREMA": "MERCADO LIVRE - EXTREMA", "shopee": "SHOPEE",
    "WEBCONTINENTAL": "WEBCONTINENTAL", "WAPSTORE - ENGAGE": "WAPSTORE - ENGAGE",
    "LEROY - EXTREMA": "LEROY - EXTREMA", "BRADESCO SHOP": "BRADESCO SHOP",
    "TIKTOK": "TIKTOK", "AMAZON DBA": "AMAZON DBA"
}

CARRIERS = {
    # Forma curta canonica (Intelipost)
    "Atual Cargas": "ATUAL",
    "Brasil Web Standard": "BRASIL WEB",
    "Favorita Transportes": "FAVORITA",
    "FrontLog": "FRONTLOG",
    "Generoso": "GENEROSO",
    "JadLog": "JADLOG",
    "Logan Express": "LOGAN",
    "MMA Cargas Expressas": "MMA",
    "Patrus": "PATRUS",
    "Reboucas": "REBOUÇAS", "REBOUCAS": "REBOUÇAS",
    "Rede Sul": "REDE SUL",
    "Rio Express Cargas": "RIO EXPRESS",
    "TJB": "TJB",
    "Total": "TOTAL",
    "Trilog Express": "TRILOG",
    "Via Pajucara": "PAJUÇARA", "VIA PAJUCARA": "PAJUÇARA",

    # ---------- Variantes Sysemp (com sufixos SERRA / EXTREMA / SDF / IDs de empresa) ---------- #
    # BRASIL WEB
    "BRASIL WEB TRANSPORTES EXTREMA SDF 21": "BRASIL WEB",
    "BRASIL WEB TRANSPORTES SERRA SDF 18": "BRASIL WEB",
    "BRASIL WEB TRANSPORTES SERRA 19": "BRASIL WEB",
    "BRASIL WEB TRANSPORTES SERRA 18": "BRASIL WEB",
    "BRASIL WEB TRANSPORTES SERRA 18 SDF": "BRASIL WEB",
    "BRASIL WEB SP SDF 21": "BRASIL WEB",
    "BRASIL WEB STANDARD 21": "BRASIL WEB",
    "BRASIL WEB NOVA EXTREMA 21": "BRASIL WEB",

    # FRONTLOG
    "FRONTLOG EXTREMA SDF 21": "FRONTLOG",
    "FRONTLOG EXTREMA 21": "FRONTLOG",

    # JADLOG
    "JADLOG LOGISTICA SERRA SDF 18": "JADLOG",
    "JADLOG TRANSPORTES SERRA 18": "JADLOG",
    "JADLOG TRANSPORTES SERRA 19": "JADLOG",

    # MMA
    "MMA CARGAS EXPRESSAS 21": "MMA",
    "MMA TRANSPORTES NOVA EXTREMA 21 SDF": "MMA",
    "MMA TRANSPORTES SERRA SDF 18": "MMA",
    "MMA TRANSPORTES SERRA 18": "MMA",
    "MMA TRANSPORTES SERRA 19": "MMA",

    # REDE SUL
    "REDE SUL SERRA 18": "REDE SUL",
    "REDE SUL SERRA 19": "REDE SUL",
    "REDE SUL SERRA SDF 18": "REDE SUL",

    # TJB
    "TJB - TRANSPORTADORA 21": "TJB",
    "TJB - TRANSPORTADORA SERRA 18": "TJB",
    "TJB - TRANSPORTADORA SERRA 19": "TJB",
    "TJB - TRANSPORTADORA SERRA SDF 18": "TJB",
    "TJB - TRANSPORTADORA SERRA SDF 19": "TJB",
    "TJB - TRANSPORTADORA SDF 21": "TJB",

    # TOTAL
    "TOTAL EXPRESS SERRA 18": "TOTAL",
    "TOTAL EXPRESS SERRA 19": "TOTAL",
    "TOTAL TRANSPORTADORA 21": "TOTAL",
    "TOTAL TRANSPORTADORA SERRA SDF 18": "TOTAL",
    "TOTAL NOVA EXTREMA 21 SDF": "TOTAL",

    # TRILOG
    "TRILOG EXPRESS 21": "TRILOG",
    "TRILOG EXPRESS SERRA 18": "TRILOG",
    "TRILOG EXPRESS SERRA 19": "TRILOG",
    "TRILOG EXPRESS SERRA SDF 18": "TRILOG",
    "TRILOG NOVA EXTREMA SDF 21": "TRILOG",

    # FAVORITA
    "FAVORITA TRANSPORTES SERRA 18": "FAVORITA",
    "FAVORITA TRANSPORTES SERRA 19": "FAVORITA",
    "FAVORITA TRANSPORTES SERRA SDF 18": "FAVORITA",
    "FAVORITA TRANSPORTES EXTREMA SDF 21": "FAVORITA",
    "FAVORITA NOVA EXTREMA 21": "FAVORITA",

    # RIO EXPRESS
    "RIO EXPRESS SERRA 18": "RIO EXPRESS",
    "RIO EXPRESS SERRA 19": "RIO EXPRESS",
    "RIO EXPRESS SERRA SDF 18": "RIO EXPRESS",
    "RIO EXPRESS SERRA SDF 19": "RIO EXPRESS",

    # PAJUÇARA  (inclui typo PAJUÇURA mantido conforme fonte)
    "VIA PAJUÇARA NOVA EXTREMA SDF 21": "PAJUÇARA",
    "VIA PAJUÇARA SERRA 18": "PAJUÇARA",
    "VIA PAJUÇARA SERRA 19": "PAJUÇARA",
    "VIA PAJUÇARA SERRA SDF 18": "PAJUÇARA",
    "VIA PAJUÇURA NOVA EXTREMA 21": "PAJUÇARA",

    # ATUAL
    "ATUAL CARGAS SERRA 18": "ATUAL",
    "ATUAL CARGAS SERRA 19": "ATUAL",
    "ATUAL TRANSPORTADORA SERRA SDF 18": "ATUAL",

    # REBOUÇAS
    "REBOUÇAS SERRA 16": "REBOUÇAS",
    "REBOUÇAS SERRA 18": "REBOUÇAS",
    "REBOUÇAS SERRA 19": "REBOUÇAS",
    "REBOUÇAS SERRA SDF 18": "REBOUÇAS",

    # PATRUS
    "PATRUS NOVA EXTREMA SDF 21": "PATRUS",
    "PATRUS TRANSPORTES EXTREMA 21": "PATRUS",
    "PATRUS TRANSPORTES SERRA 18": "PATRUS",
    "PATRUS TRANSPORTES SERRA 19": "PATRUS",
    "PATRUS TRANSPORTADORA SERRA SDF 18": "PATRUS",

    # GENEROSO
    "GENEROSO SERRA 18": "GENEROSO",
    "GENEROSO SERRA 19": "GENEROSO",
    "GENEROSO TRANSPORTES SERRA SDF 18": "GENEROSO",

    # Outros (passam pelo dicionario para preservar a grafia desejada)
    "AMAZON CLASSIC FBA BETIM": "AMAZON CLASSIC FBA BETIM",
    "TIKTOK": "TIKTOK",
}

OCCURRENCES = {
    "AGUARDANDO DADOS": "VERIFICAR", "(TOTAL) FALTA DE ARQUIVO": "VERIFICAR",
    "AGUARDANDO INSTRUÇÃO": "VERIFICAR", "ÁREA DE RISCO": "ÁREA DE RISCO",
    "ÁREA NÃO ATENDIDA": "ÁREA NÃO ATENDIDA", "AVERIGUAR FALHA NA ENTREGA": "VERIFICAR",
    "ARREPENDIMENTO": "BLOQUEADO PELO REMETENTE", "AUSENTE": "AUSENTE", "BUSCA": "EXTRAVIO",
    "CARGA DESCARTADA": "VERIFICAR", "AVARIA": "AVARIA", "CARGA ERRADA": "VERIFICAR",
    "CARGA ROUBADA": "ROUBO", "CARGA RECUSADA PELO DESTINATARIO": "RECUSADO",
    "CARTA DE CORREÇÃO": "VERIFICAR", "CLIENTE ALEGA FALTA DE MERCADORIA": "VERIFICAR",
    "DESTINATÁRIO DESCONHECID0": "DESTINATÁRIO DESCONHECIDO", "DESTINATÁRIO AUSENTE": "AUSENTE",
    "DEVOLUÇÃO INDEVIDA": "VERIFICAR", "DEVOLUÇÃO POR ATRASO": "VERIFICAR",
    "DESTINATÁRIO MUDOU-SE": "ENDEREÇO NÃO LOCALIZADO", "DUPLICIDADE": "VERIFICAR",
    "DESTINATÁRIO NÃO LOCALIZADO": "ENDEREÇO NÃO LOCALIZADO", "DIFICIL ACESSO": "ÁREA DE RISCO",
    "ENTREGUE E CANCELADO": "VERIFICAR", "ENDEREÇO INSUFICIENTE": "ENDEREÇO NÃO LOCALIZADO",
    "ERRO DE EXPEDIÇÃO": "VERIFICAR", "ESTABELECIMENTO FECHADO": "AUSENTE",
    "FURTO / ROUBO": "ROUBO", "EXTRAVIO CONFIRMADO": "EXTRAVIO", "ITEM FALTANTE": "AVARIA PARCIAL",
    "FALHA NA ENTREGA": "VERIFICAR", "NÃO ENTROU NA UNIDADE": "VERIFICAR",
    "Mercadoria retida/liberada por Fiscalização": "NOTA RETIDA", "PARADO NA FISCALIZACAO": "NOTA RETIDA",
    "PROBLEMA OPERACIONAL": "VERIFICAR", "SEM RASTREIO": "VERIFICAR",
    "RESGATE DE MERCADORIA SOLICITADA PELO CLIENTE": "RETIRADA NA UNIDADE",
    "ANÁLISE FISCAL": "NOTA RETIDA", "SOLICITAÇÃO DE ACAREAÇÃO": "EM PROCESSO DE INVESTIGAÇÃO",
    "VIA INTERDITADA": "VERIFICAR", "CORRECAO INFORMACAO DE EVENTO": "VERIFICAR",
    "ZONA RURAL": "VERIFICAR", "CARGA INCOMPLETA": "AVARIA PARCIAL"
}

# Colunas Finais Padrão (Fluxos Intelipost / E-mail)
FINAL_COLUMNS = [
    'Transportadora', 'Chave NF', 'Nota Fiscal', 'UF',
    'Data Tratativa', 'Marketplace', 'Pedido', 'Ocorrência de Entrega'
]

# Colunas Finais — Fluxo Validação de Transportadora
# Ordem fixa, conforme especificação operacional do módulo.
FINAL_COLUMNS_VALIDACAO = [
    'DIA DA TRATATIVA',
    'DATA PEDIDO',
    'DATA PREVISTA',
    'UF',
    'TRANSPORTADORA',
    'PEDIDO INTELIPOST',
    'CHAVE DA NF',
    'MARKETPLACE',
    'N° PEDIDO',
    'NOTA FISCAL',
    'STATUS DA TRANSPORTADORA',
]
